name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up openJDK
        uses: actions/setup-java@v1
        with:
          java-version: '15'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: make build
      - name: Setup Java JDK
        uses: actions/setup-java@v2.2.0

